### ISSUE TITLE
Plans for an API to abort requests?

### ISSUE THREAD

**Issue by mattjbray** [evancz/elm-http#17]
Firstly, thank you for Elm - this stuff is awesome!

As a toy project, I've implemented [staltz/flux-challenge](https://github.com/staltz/flux-challenge) in Elm.  The spec requires the ability to cancel XmlHttpRequests.

I [hacked this together](https://github.com/evancz/elm-http/compare/master...mattjbray:master) for a quick solution, but do you have plans produce a sane API to abort requests?

**Comment by evancz** [comment]
Yep, the plan is to add `kill : ThreadID -> Task x ()` to core. This will allow you to use the existing `spawn` function to start a bunch of stuff and then kill it if necessary.

**Comment by mattjbray** [comment]
@evancz it looks like elm-http has learned how to abort requests when the Task is killed.

However I haven't yet seen `spawn`/`kill` used outside of effect managers. Could you give me a pointer on how to use this to abort an HTTP request in application code?

My issue is that, after using `spawn : Task x a -> Task y Id`, I'm no longer able to get at the result `a` of the request. So it looks like I can either get my result `a`, or the `Id` of the process, but not both.

**Comment by evancz** [comment]
You are correct. You can read more about the future plans for this [here](http://package.elm-lang.org/packages/elm-lang/core/4.0.0/Process). A decent amount more work needs to be done before interprocess communication is ready to go.

**Comment by roine** [comment]
+1 I'm also looking for that feature.
