### ISSUE TITLE
post can't send json

### ISSUE THREAD

**Issue by simonh1000** [evancz/elm-http#22]
You elm-http library is rightly geared towards json. Both `get` and `post` pass the returned values through json decoders. 

However, sending json to a server is effectively not supported - in particular a standard node/express setup does not pick up a json string posted by `Http.post`. This is because the headers for `send` are hard coded to `[]`, while Express expects `[("Content-type", "application/json")]`. Several Elm users have had similar difficulties - see https://groups.google.com/forum/#!topic/elm-discuss/Zpq9itvtLEY

According to [stackoverflow](http://stackoverflow.com/questions/477816/what-is-the-correct-json-content-type) `"application/json"` is clearly the right choice for json data.

Note also this from the [W3C](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.1):

`The content type "application/x-www-form-urlencoded" is inefficient for sending large quantities of binary data or text containing non-ASCII characters. The content type "multipart/form-data" should be used for submitting forms that contain files, non-ASCII data, and binary data.` 

As things stand i think there are four options for:
1. do nothing, at which point I'm not sure anyone can make use of Http.post
2. make `[("Content-type", "application/json")]` the default
3. make `[("Content-type", "application/x-www-form-urlencoded")]`
4. refactor `Http.post` to take a Content-Type parameter.

To my mind 2 and 4 have the strongest claim. Let me know what you think and i can submit a PR.

**Comment by evancz** [comment]
What is the difference between `application/x-www-form-urlencoded` and `application/json` like someone suggested in the thread?

I need to know _why_ something would be a better default. Can you edit the original comment to clarify this and as much of [this checklist](https://github.com/process-bot/the-process/blob/master/issues.md#issue-checklist) as makes sense here? From there, add a comment to this thread so I get notified, I'll delete these two comments, and we can continue from there.

**Comment by simonh1000** [comment]
Evan, I've done some more research.

**Comment by Istar-Eldritch** [comment]
I agree with @simonh1000, I am not happy with magic, so, in my humble opinion forcing the Http.post to have a Content-Type parameter is the best option to avoid unexpected behaviour, in the other hand the send function does something really close to it already, so is probalby not worth to mess with the current implementation.

Getting advantage of currying makes easy to define a default function based on `send` with the conten-type for use in the rest of the program. I show this in the comment for the formUrlEncodedPost body formatter in the pull request #20 

If to choose one default header `application/json` is the clear winner.

**Comment by punund** [comment]
Both `application/x-www-form-urlencoded` and `application/json` (and `multipart/form-data`) have their uses, so any, or none can be default, doesn't matter that much.

The real problem is that at present `Http.post` doesn't set any `Content-Type` header at all, which is somewhat in contradiction with [https://www.w3.org/Protocols/rfc2616/rfc2616-sec7.html](standards) requiring that any request with entity-body SHOULD include the appropriate content type, otherwise the payload is treated as `application/octet-stream` so any sane server is correctly not seeing values being sent, be it json  or urlencoded.

**Comment by simonh1000** [comment]
@evancz Looks like this is not addressed in the upcoming release. Leaving `post` with no options set makes it useless for most, and pushes us all to `send`. I would suggest picking one of the options above, or adding a new parameter to the post function so that users can set a content type.

**Comment by maximsch2** [comment]
Maybe adding a function called `postJson` solve the problem? Although I agree with the sentiment that a regular `post` is somewhat useless.

**Comment by mattludwigs** [comment]
I agree with @simonh1000, I struggled for a while to send JSON data to my backend using `Http.post` until I read the the src to see the headers are set to `[]` with no way of changing it using `Http.post`. I had to start using `Http.send` for everything post related. I second @simonh1000's solution to parametrize the headers or the content-type.

**Comment by galderz** [comment]
@mattludwigs Hmmmm, I also looked at the source and [saw headers set to []](https://github.com/evancz/elm-http/blob/3.0.1/src/Http.elm#L403). However, I'm not sure that's the full story because having debugged a POST request sent from Elm 0.17 using `Http.post`, I see `'content-type': 'text/plain;charset=UTF-8'`.

**Comment by mattludwigs** [comment]
@galderz I am wondering if somewhere the Http post request content type is defaulting to `text/plain;charset=UTF-8` outside of the Elm code. However, I think it would still be good to parametrize the headers or the content-type for the `Http.post`, or provide a `Http.jsonPost` (maybe there is a better name?) function where the content type is set to JSON (this is suggested above as well). But it would at least seem more flexible, as of right now, to parametrize the headers for `Http.post`.

**Comment by mattludwigs** [comment]
One area where parametrizing the headers is a little more tricky is that the type signature `(String, String)` does not account for all header options like content-length which would probably need to be `(String, Int)`. However, when I think about the main use case for posting data there is normally some other authorization data coming alone with it, so it would still seem more flexible to parametrize the hole header rather than just a piece of it.

Maybe using an extensible record or something might help, but I am not sure what the best solution would be. Plus, if there is a change away from a `List` being passed into the headers this line might need to be updated: https://github.com/evancz/elm-http/blob/3.0.1/src/Native/Http.js#L53

**Comment by garbas** [comment]
I'm seeing the same problem ... [here](https://gist.github.com/garbas/f8a9cbe5fb2d619bb89c8df99b05ae92) is my snippet of code that is suppose to work

**Comment by FrontierPsychiatrist** [comment]
Just want to chime in and say that I have to make a standard POST request pretty complicated with `send` just because `post` does not allow a JSON body.

The Http documentation actually states one should use `Http.string` for JSON, but a standard Spring backend will just return 415 (content type not allowed).

**Comment by mattludwigs** [comment]
@FrontierPsychiatrist & @garbas maybe this package can offer a solution: [elm-http-builder](http://package.elm-lang.org/packages/lukewestby/elm-http-builder/2.0.0/)? I am going to be putting a PR up for this a little later today (I started fixing a while ago, but got busy with work), but I am not sure we should be using this package over the `elm-http-builder` or this package over `elm-http-builder`.

**Comment by garbas** [comment]
@mattludwigs tnx, willl give it a try

**Comment by mattludwigs** [comment]
@garbas @FrontierPsychiatrist @simonh1000 @galderz: just opened a PR. It is my first Elm related PR so any feed back would be great!

I just made the `post` take request headers as a parameter. I am not sold that this is the only or best solution, so let me know your thoughts! Thanks!

**Comment by garbas** [comment]
@mattludwigs was playing with you `elm-http-builder` and I really like how you build HTTP requests. much nicer experience then with `elm-http`. it would be nice to see both package converge ideas and that this lands in `elm-lang`/`elm-community`. if i understood correctly how @evancz envisions elm package system to work.

**Comment by larryweya** [comment]
Came across this as well as I needed to set the content type to application/json, would it make sense to at least have a headers parameter?

**Comment by chakrit** [comment]
`Content-Type` is better implemented as property of [`Body`](http://package.elm-lang.org/packages/evancz/elm-http/3.0.1/Http#Body). This is how it is done in [OkHttp](https://github.com/square/okhttp). Of all HTTP libs I've used I think this is the best approach.

`Content-Type` is inherently a property of the content you are sending. So following this approach you'd specify the type of the content when you are building the `Body` itself which is great for code locality and single responsibility. The engine do not need another configuration knob, it just needs to read the type from the body.

**Comment by jergason** [comment]
@chakrit Setting the `Content-Type` on the body feels counter-intuitive to me, since it is set via the headers in HTTP itself.

**Comment by magopian** [comment]
I added a few questions on the PR itself: https://github.com/evancz/elm-http/pull/44#issuecomment-244904492

**Comment by simonh1000** [comment]
I'm closing this as I see a fix is coming with 0.18

**Comment by thielema** [comment]
How does elm-0.18 solve the problem? evancz/elm-http-3.0.1 still seems to be the same.

**Comment by simonh1000** [comment]
if you use expectJson then 'application/json' gets added to the headers. All is good

**Comment by thielema** [comment]
I only see this function: http://package.elm-lang.org/packages/elm-lang/http/latest/Http#expectJson with that name. But it is for response bodies not for request bodies and it is in package `http` not `elm-http`. What `expectJson` are you referring to?

**Comment by simonh1000** [comment]
http://package.elm-lang.org/packages/elm-lang/http/1.0.0/Http#expectJson

**Comment by maximsch2** [comment]
I agree with @thielema, `expectJson` is not what this issue is about. On the other hand, it looks like using `jsonBody` (http://package.elm-lang.org/packages/elm-lang/http/1.0.0/Http#jsonBody) should do the trick.

**Comment by simonh1000** [comment]
As I created the issue, I think we can safely assume that is about exactly this! ;-)

Feel free to create a new issue if you have one

**Comment by maximsch2** [comment]
`expectJson` is about parsing the response, but the the first post in the issue is talking about the request header...
In any case, the issue seems to be resolved with `jsonBody`, so no need to create anything new.

**Comment by thielema** [comment]
On Mon, 21 Nov 2016, Maxim Grechkin wrote:

> expectJson is about parsing the response, but the the first post in the issue is talking about the request
> header...
> In any case, the issue seems to be resolved with jsonBody, so no need to create anything new.

Are Body of elm-lang/http and evancz/elm-http compatible? Or are we 
supposed to replace evancz/elm-http by elm-lang/http? If so, I would be 
missing the Http.url function.

**Comment by simonh1000** [comment]
Note that evancz/elm-http is not compatible wth 0.18

**Comment by amitu** [comment]
@simonh1000 what is the replacement for Http.url in "elm-lang/http"?
