### ISSUE TITLE
Introduce a `Method` type for `verb`

### ISSUE THREAD

**Issue by menelaos** [evancz/elm-http#23]
Currently, the `verb` field in `Request` takes a `String`.

``` elm
type alias Request = 
    { verb : String
    , headers : List (String, String)
    , url : String
    , body : Body
    }
```

This could be made more type-safe by using a `Method` type similiar to how e.g.
[Snap](http://hackage.haskell.org/package/snap-core-0.9.8.0/docs/Snap-Core.html#t:Method) does it:

``` elm
type Method 
  = GET
  | HEAD
  | POST
  | PUT
  | DELETE
  | TRACE
  | OPTIONS
  | CONNECT
  | PATCH
  | Method String
```

On a side note, I think `verb` should be renamed to `method` as
the latter term seems to be more widely used, cf. [RxJS](https://github.com/Reactive-Extensions/RxJS-DOM/blob/master/doc/operators/ajax.md#rxdomajaxsettings).

**Comment by milibopp** [comment]
The uppercase identifiers don't fit too well. Let's just make these CamelCased as usual.

**Comment by menelaos** [comment]
Personally, I'd be fine with that, too.
I'd just like to point out that according to [RFC2616](http://www.ietf.org/rfc/rfc2616.txt), Section `5.1.1`

> The method is case-sensitive.

RFC2616 has recently been supplanted by a series of RFCs, but they
also state in [RFC7230](https://tools.ietf.org/rfc/rfc7230.txt), Section `3.1.1` that

> The request method is case-sensitive.

So I guess most web developers are already used to writing the request methods in uppercase. It also makes it easier to visually distinguish them from user-defined types.

**Comment by milibopp** [comment]
Hm… that's a valid point. The question is then, I guess, how closely this library's API should mirror the underlying protocol. I don't have a strong opinion tbh, just noticed it as slightly awkward.

**Comment by evancz** [comment]
I considered this design for elm-lang/http, but decided against it. Reasons include:

  - Folks should be using helper functions in general, not primitives directly.
  - Exposing union type constructors directly is bad practice because adding another one is a breaking change.
  - If they were going to be exposed as `get` and `post`, it made more sense to just have those be helper functions, not `Method` constructors that are messier to use.
