### ISSUE TITLE
HTTP requests on different ports

### ISSUE THREAD

**Issue by langston-barrett** [evancz/elm-http#34]
How do you make an HTTP request to a port other than 80? Do you just feed a different URL, e.g. `getString "100.10.10.10:8080/endpoint"`? If so, it might be worth adding this to the examples.

**Comment by magopian** [comment]
I've just tried it (see [this gist](https://gist.github.com/magopian/6cd221c7f699100ff9b2cb7fc7394bfd)) and it seems to indeed "just work" if you specify a port number (I had `elm reactor` running).

I'm not sure how relevant it would be to add this to the examples, as it's something people would usually just try and expect to work imho.

**Comment by langston-barrett** [comment]
fair enough. feel free to close if it doesn't seem worthwhile
