### ISSUE TITLE
onStart / onProgress only good for Debug.log ?

### ISSUE THREAD

**Issue by tko** [evancz/elm-http#39]
> - `onStart` and `onProgress` allow you to monitor progress. This is useful if you want to show a progress bar when uploading a large amount of data.
>   
>   , onStart : Maybe (Task () ())
>   , onProgress : Maybe (Maybe { loaded : Int, total : Int } -> Task () ())

How can one update the model with the 'loaded' and 'total' values here? I don't see how the callbacks could be used for anything other than `Debug.log` and `succeed ()` and can't find any examples to the contrary. Shouldn't the signature be `Task () (Cmd msg)` or am I just not understanding how to trigger an update from these callbacks?

**Comment by rtfeldman** [comment]
As far as I can make out, think this API made sense in 0.16, but is no longer useful in 0.17.

**Comment by evancz** [comment]
It should become useful again once processes can communicate, as described [here](http://package.elm-lang.org/packages/elm-lang/core/4.0.1/Process#future-plans).
