### ISSUE TITLE
fromString

### ISSUE THREAD

**Issue by toastal** [evancz/elm-http#40]
`fromJson` is nice because it abstracts away `promoteError` and `handleResponse`. I have another super common use case which is just returning a plaintext string from a response and then using that value provided the task succeeds.

**Comment by magopian** [comment]
Are you looking for [getString](http://package.elm-lang.org/packages/evancz/elm-http/3.0.1/Http#getString)?

To experiment and try to understand the issue, I created [a gist](https://gist.github.com/magopian/66ad532bda717379b79fd54826a10e0d) with the two methods:
- `Http.getString`: [line 43](https://gist.github.com/magopian/66ad532bda717379b79fd54826a10e0d#file-http-getstring-elm-L43)
- `Http.fromJson`: [line 55](https://gist.github.com/magopian/66ad532bda717379b79fd54826a10e0d#file-http-fromjson-elm-L55)

Maybe I'm misunderstanding your question, and you're looking for something else?

**Comment by toastal** [comment]
Ah yes. You're right.
