### ISSUE TITLE
`uriDecode` is not total. 

### ISSUE THREAD

**Issue by Fresheyeball** [evancz/elm-http#41]
### `uriDecode` can fail at runtime

Depending on the value of the string, this function may fail.

For example:

``` elm
uriDecode "%"
```

Will throw the following error at runtime

```
Uncaught URIError: URI malformed
    at decodeURIComponent (native)
    at <anonymous>:1:1
```
### Expected behavior

Function is total and does not have the potential to throw errors.
### Recommendation

Perhaps the type of this function should be `String -> Result URIError String`

**Comment by magopian** [comment]
I can confirm that by running the following code in the [online editor](http://elm-lang.org/try)

```
import Http
import Html

main = Html.text <| Http.uriDecode "%"
```

It will display the following javascript error in the Google Chrome console:
<img width="751" alt="screen shot 2016-09-04 at 15 45 47" src="https://cloud.githubusercontent.com/assets/167767/18231301/d2278a9c-72b6-11e6-9a90-f1315e625c4d.png">
 
And a similar one in the Mozilla Firefox console:
<img width="796" alt="screen shot 2016-09-04 at 15 47 25" src="https://cloud.githubusercontent.com/assets/167767/18231303/e93e396a-72b6-11e6-91b0-74e6519dfcf2.png">

And in the elm-repl:
<img width="328" alt="screen shot 2016-09-04 at 15 49 32" src="https://cloud.githubusercontent.com/assets/167767/18231313/325b2158-72b7-11e6-9d4b-ca3eed3bb838.png">

**Comment by evancz** [comment]
@Fresheyeball, how did you discover this? Was it in production? Or were you stress testing the function? Any context like this would be extremely helpful!

**Comment by Fresheyeball** [comment]
I was able to work around this using Native to avoid issues in production. Basically data is coming in from the server, and I can't control what that looks like. A string sent by the server should have been encodable but was not.

**Comment by evancz** [comment]
Great, thanks for the background information! I have it as `String -> Maybe String` in the revised API I am drafting.

**Comment by Fresheyeball** [comment]
I think thats fine. Personally I would prefer Result so that its more
debuggable. Otherwise it might be unclear as to why it failed.

**Comment by evancz** [comment]
I looked at the actual error, and it seems it provides no additional information. If you can show that more information is ever provided, I think it makes sense to have as well.

**Comment by Fresheyeball** [comment]
I just checked around. You are right, the actual error thrown in JavaScript is useless. `Maybe` wins.

**Comment by evancz** [comment]
Should be fixed in elm-lang/http
