### ISSUE TITLE
CORS Example does not work

### ISSUE THREAD

**Issue by ghost** [evancz/elm-http#45]
Hi, tried the CORS example from the docs here:

```
    corsPost : Request
    corsPost =
        { verb = "POST"
        , headers =
            [ ("Origin", "http://elm-lang.org")
            , ("Access-Control-Request-Method", "POST")
            , ("Access-Control-Request-Headers", "X-Custom-Header")
            ]
        , url = "http://example.com/hats"
        , body = empty
        }
```

It does not work, my browser sends options, as if it's trying to do a preflight request. Does Elm not manage CORS as xhrRequest does now automatically in JS ?

**Comment by evancz** [comment]
I can't tell what "as xhrRequest does now automatically in JS" means. Can you open a new issue with an http://sscce.org/ so I can reproduce what you are seeing?

**Comment by ghost** [comment]
@evancz sorry, i was too quick in this, i hadn't enabled cors on my webserver...

**Comment by ghost** [comment]
no issue then

**Comment by evancz** [comment]
Cool, glad it is working!
