### ISSUE TITLE
Difference between evancz/elm-http and elm-lang/http

### ISSUE THREAD

**Issue by infi-pc** [evancz/elm-http#51]
When i was trying to get some documentation about `elm-lang/http` google took me here: http://package.elm-lang.org/packages/evancz/elm-http/latest instead of http://package.elm-lang.org/packages/elm-lang/http/latest/Http
For me as begginner it looked same. I don't exactly understand difference between this and `elm-lang/http`, but it really confused me. Can you please explain differences between this two libraries? preferably in readme :) thx

**Comment by ssbb** [comment]
@infi-pc according to 0.17 -> 0.18 upgrading guide, this repo just moved to elm-lang/http - https://github.com/elm-lang/elm-platform/blob/master/upgrade-docs/0.18.md
