### ISSUE TITLE
Body not being sent with "GET" requests

### ISSUE THREAD

**Issue by vitiral** [evancz/elm-http#53]
I have the following code:

```
fetchAll : Cmd AppMsg
fetchAll =
  let
    value = getArtifactsRequestEncoded 1
    body = Http.jsonBody value
    request = Http.request
      { method = "PUT"
      , headers =
        [ Http.header "Content-Type" "application/json"
        ]
      , url = fetchAllUrl
      , body = body
      , expect = Http.expectJson getArtifactsResponseDecoder
      , timeout = Nothing
      , withCredentials = False
      }
  in
    Http.send newArtifactsMsg request
```

If I switch `method = "PUT"` to `method = "GET"` this no longer sends any data in the body!

> For reproducability, the bug was found in my project at [this commit](https://github.com/vitiral/rst/commit/2545b57458c13adebe0dd07ae579ac222f7bc573). The elm app is in `web-ui` and my MVP backend is written in rust in `web-ui/api`. However, I wouldn't advise you go to the trouble of reproducing (let me know if you need more info).

**Comment by evancz** [comment]
GET requests have no body. That's an HTTP thing, not an Elm thing.

**Comment by vitiral** [comment]
Oh thanks! Sorry I didn't know that, I'm completely new to web stuff. Elm is a really great way to start though!
