### ISSUE TITLE
Http.multipart: Uncaught ReferenceError: type is not defined

### ISSUE THREAD

**Issue by Dobiasd** [evancz/elm-http#6]
The runtime error occurs in

```
function multipart(dataList)
```

in the following line:

```
if (type === 'StringData')
```

online demo: http://daiw.de/share/elm/http.post/
Main.elm: https://gist.github.com/Dobiasd/b271779f7e13afcb8ddf
elm-package.json: https://gist.github.com/Dobiasd/df75cc6fcfb2342f7209

edit 2015-07-06: Just tested it with Elm Platform 0.15.1 instead of 0.15 and the problem still exists.

**Comment by amcvega** [comment]
I ran into this as well. I created a pull request to fix this and the further bug of multipart data not being sent at all. https://github.com/evancz/elm-http/pull/13
