### ISSUE TITLE
Request: special error when failure is due to cross origin permissions

### ISSUE THREAD

**Issue by chendrix** [evancz/elm-http#9]
For reference: elm-lang/package.elm-lang.org#50

If you use `Http.getString` to get a URL from a **different domain** than your elm code is being run on and the server serving the URL does not have CORS turned on, a runtime exception, e.g.

```
XMLHttpRequest cannot load http://package.elm-lang.org/packages/elm-lang/core/latest/README.md. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.
```

is raised

My thought is it should be captured in the the `Http.Error` of the returned `Task`

**Comment by evancz** [comment]
Can you look up how to catch CORS issues in JS? Seems reasonable to model this in `Http.Error` and `Http.RawError`.

**Comment by codedmart** [comment]
@evancz It still might be reasonable to model this in `Http.Error` and `Http.RawError` to give some feedback to the user using elm-http, but with your recent merge of #7 you can set `withCredentials` to avoid this problem all together.

**Comment by magopian** [comment]
According to http://stackoverflow.com/a/19325710 and http://stackoverflow.com/a/6734427, there is no way to detect a failure caused by a CORS issue in javascript.

**Comment by evancz** [comment]
Thanks @magopian! As I understand it, @chendrix is not reporting a runtime exception that causes Elm programs to crash. The request still results in an `Http.Error`. It is that browsers show red stuff in the console even though the code runs fine. The links shared by @magopian suggest that this is how it _should_ work.
